output_path: ./output
cameras:
  - name: Camera1
    stream_url: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4
    split: 10
  - name: Camera2
    stream_url: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4
    split: 10
